//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class mezczyzna
    {
        public byte ID { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public byte Wiek { get; set; }
        public string Miejscowosc { get; set; }
        public Nullable<byte> Zainteresowanie_1 { get; set; }
        public Nullable<byte> Zainteresowanie_2 { get; set; }
        public Nullable<byte> Zainteresowanie_3 { get; set; }
        public Nullable<byte> status_zwiazku_ID { get; set; }
        public Nullable<byte> firma_ID { get; set; }
        public Nullable<byte> znak_zodiaku_ID { get; set; }
        public Nullable<byte> wyksztalcenie_ID { get; set; }
        public Nullable<byte> zwierzatko_ID { get; set; }
        public Nullable<byte> religia_ID { get; set; }
        public Nullable<byte> alkohol_ID { get; set; }
        public Nullable<byte> papierosy_ID { get; set; }
    
        public virtual alkohol alkohol { get; set; }
        public virtual firma firma { get; set; }
        public virtual papierosy papierosy { get; set; }
        public virtual religia religia { get; set; }
        public virtual status_zwiazku status_zwiazku { get; set; }
        public virtual wyksztalcenie wyksztalcenie { get; set; }
        public virtual zainteresowanie zainteresowanie { get; set; }
        public virtual zainteresowanie zainteresowanie1 { get; set; }
        public virtual zainteresowanie zainteresowanie2 { get; set; }
        public virtual znak_zodiaku znak_zodiaku { get; set; }
        public virtual zwierzatko zwierzatko { get; set; }
    }
}
